# Generated by Django 5.2.8 on 2025-12-03 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='my_user',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'my_user')},
        ),
    ]
