# Generated by Django 5.2.8 on 2025-12-03 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_user_like_my_user_alter_like_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pub_date',
        ),
    ]
