# Generated by Django 5.2.9 on 2025-12-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_comment_likes_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars'),
        ),
    ]
